export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS';

export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
// export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
