auth0PublicKey = './server/voting-tornado.pem'
dbServer = 'mongoDbServer/databaseName'
dbUser = 'db-user'
dbPassword = 'password'
database_name = 'databaseName'

auth0_clientId = '<clientID>'
auth0_secret = 'client_secret'
auth0_authorization_url = 'https://<app>.us.webtask.io/<key>/api'
auth0_url = 'https://<app>.auth0.com'
